### PR TITLE
Don't allow JavaDoc @author tags

### PR DESCRIPTION
**Pull request by wiebeck**
I believe `author` tags in JavaDocs on classes have no value whatsoever. In distributed development there is no such thing as the "author of a class", at least not over time. This video from Google I/O 2008 also came to the same conclusion: https://www.youtube.com/watch?v=-F-3E8pyjFo&t=1173s (be sure to start at around 19:34 into the video).

See also:

- https://www.vojtechruzicka.com/stop-using-javadoc-author-tag/
- https://stackoverflow.com/a/17271433
- https://www.databasesandlife.com/dont-use-the-author-javadoc-tag/
- https://www.hodler.co/2015/10/11/author-tag-in-javadoc/

... and many others.

### CODE REVIEW

**Review by bockriege — APPROVED** [review]

**Review by enqueue — COMMENTED** [review]
I think it's more straightforward to use something like this, perhaps customizing the error message.

```
<module name="JavadocType">
    <property name="authorFormat" value="^$"/>
</module>
```

**Comment by wiebeck** [comment]
> I think it's more straightforward to use something like this, perhaps customizing the error message.
> 
> ```
> <module name="JavadocType">
>     <property name="authorFormat" value="^$"/>
> </module>
> ```

Wouldn't this allow the following?
```java
/**
 * @author
 */
```
The regexp check is more lines, yes, but it would also catch these "things". ;)

**Comment by enqueue** [comment]
> > I think it's more straightforward to use something like this, perhaps customizing the error message.
> > ```
> > <module name="JavadocType">
> >     <property name="authorFormat" value="^$"/>
> > </module>
> > ```
> 
> Wouldn't this allow the following?
> 
> ```java
> /**
>  * @author
>  */
> ```

No

**Comment by wiebeck** [comment]
@enqueue Unfortunately your proposal with `JavadocType / authorFormat` doesn't work although it's really small and (kind of) intuitive. When I **remove** the `@author tag` completely or **make it empty** it gives...

> Type Javadoc comment is missing @author tag.

... in both cases. :-( Any non-empty `@author` tag yields...

> Type Javadoc tag @author must match pattern '^$'.

I think we need to stick with the initial proposal.

**Comment by enqueue** [comment]
Just remove the JavaDoc.

**Pull request merged**
